name: CMake Desktop

on:
  push:
    paths:
      - 'desktop/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: |
        mkdir desktop/build-${{ matrix.os }}
        cd desktop/build-${{ matrix.os }}
        cmake .. 
        cmake --build .
        cd ../../
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: All-Make-${{ matrix.os }}
        path: ${{ github.workspace }}/desktop/build-${{ matrix.os }}
