name: Format Java

on:
  push:
    paths:
    	- 'reformating.txt'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
  	- name: begin
    	uses: actions/checkout@v3
    - name: formating_goole
    	uses: axel-op/googlejavaformat-action@v3
      with:
        args: "--replace"